//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarketer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Consumes = new HashSet<Consume>();
        }
    
        public int MemID { get; set; }
        public string MemName { get; set; }
        public string MemGender { get; set; }
        public string MemAddr { get; set; }
        public Nullable<int> MemPhoneNO { get; set; }
        public Nullable<long> CardNO { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual ICollection<Consume> Consumes { get; set; }
    }
}
