//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarketer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffID { get; set; }
        public int StoreID { get; set; }
        public string StaffName { get; set; }
        public string StaffGender { get; set; }
        public Nullable<int> StaffAge { get; set; }
        public Nullable<decimal> StaffWage { get; set; }
        public string StaffAddr { get; set; }
        public Nullable<int> StaffPhoneNO { get; set; }
    
        public virtual ChainStore ChainStore { get; set; }
        public virtual Work Work { get; set; }
    }
}
