//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Inventory__Store__21B6055D", "ChainStore", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.ChainStore), "Inventory", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SuperMarketer.Inventory), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Merchandi__Store__173876EA", "ChainStore", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.ChainStore), "Merchandise", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SuperMarketer.Merchandise), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Staff__StoreID__1273C1CD", "ChainStore", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.ChainStore), "Staff", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SuperMarketer.Staff), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Work__StoreID__1DE57479", "ChainStore", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.ChainStore), "Work", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SuperMarketer.Work), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Consume__MemID__25869641", "Member", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.Member), "Consume", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SuperMarketer.Consume), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Consume__MerchID__24927208", "Merchandise", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.Merchandise), "Consume", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SuperMarketer.Consume), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Inventory__Merch__20C1E124", "Merchandise", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.Merchandise), "Inventory", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SuperMarketer.Inventory), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Merchandi__Vendo__182C9B23", "Vendor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.Vendor), "Merchandise", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SuperMarketer.Merchandise), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Stock__MerchID__286302EC", "Merchandise", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.Merchandise), "Stock", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SuperMarketer.Stock), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Work__StaffID__1CF15040", "Staff", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.Staff), "Work", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SuperMarketer.Work), true)]
[assembly: EdmRelationshipAttribute("StoreDBModel", "FK__Stock__VendorID__29572725", "Vendor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SuperMarketer.Vendor), "Stock", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SuperMarketer.Stock), true)]

#endregion

namespace SuperMarketer
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class StoreDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“StoreDBEntities”部分中的连接字符串初始化新 StoreDBEntities 对象。
        /// </summary>
        public StoreDBEntities() : base("name=StoreDBEntities", "StoreDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StoreDBEntities 对象。
        /// </summary>
        public StoreDBEntities(string connectionString) : base(connectionString, "StoreDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 StoreDBEntities 对象。
        /// </summary>
        public StoreDBEntities(EntityConnection connection) : base(connection, "StoreDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ChainStore> ChainStores
        {
            get
            {
                if ((_ChainStores == null))
                {
                    _ChainStores = base.CreateObjectSet<ChainStore>("ChainStores");
                }
                return _ChainStores;
            }
        }
        private ObjectSet<ChainStore> _ChainStores;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Consume> Consumes
        {
            get
            {
                if ((_Consumes == null))
                {
                    _Consumes = base.CreateObjectSet<Consume>("Consumes");
                }
                return _Consumes;
            }
        }
        private ObjectSet<Consume> _Consumes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Inventory> Inventories
        {
            get
            {
                if ((_Inventories == null))
                {
                    _Inventories = base.CreateObjectSet<Inventory>("Inventories");
                }
                return _Inventories;
            }
        }
        private ObjectSet<Inventory> _Inventories;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Member> Members
        {
            get
            {
                if ((_Members == null))
                {
                    _Members = base.CreateObjectSet<Member>("Members");
                }
                return _Members;
            }
        }
        private ObjectSet<Member> _Members;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Merchandise> Merchandises
        {
            get
            {
                if ((_Merchandises == null))
                {
                    _Merchandises = base.CreateObjectSet<Merchandise>("Merchandises");
                }
                return _Merchandises;
            }
        }
        private ObjectSet<Merchandise> _Merchandises;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Staff> Staffs
        {
            get
            {
                if ((_Staffs == null))
                {
                    _Staffs = base.CreateObjectSet<Staff>("Staffs");
                }
                return _Staffs;
            }
        }
        private ObjectSet<Staff> _Staffs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Stock> Stocks
        {
            get
            {
                if ((_Stocks == null))
                {
                    _Stocks = base.CreateObjectSet<Stock>("Stocks");
                }
                return _Stocks;
            }
        }
        private ObjectSet<Stock> _Stocks;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Vendor> Vendors
        {
            get
            {
                if ((_Vendors == null))
                {
                    _Vendors = base.CreateObjectSet<Vendor>("Vendors");
                }
                return _Vendors;
            }
        }
        private ObjectSet<Vendor> _Vendors;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Work> Works
        {
            get
            {
                if ((_Works == null))
                {
                    _Works = base.CreateObjectSet<Work>("Works");
                }
                return _Works;
            }
        }
        private ObjectSet<Work> _Works;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 ChainStores EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToChainStores(ChainStore chainStore)
        {
            base.AddObject("ChainStores", chainStore);
        }
    
        /// <summary>
        /// 用于向 Consumes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToConsumes(Consume consume)
        {
            base.AddObject("Consumes", consume);
        }
    
        /// <summary>
        /// 用于向 Inventories EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToInventories(Inventory inventory)
        {
            base.AddObject("Inventories", inventory);
        }
    
        /// <summary>
        /// 用于向 Members EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMembers(Member member)
        {
            base.AddObject("Members", member);
        }
    
        /// <summary>
        /// 用于向 Merchandises EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMerchandises(Merchandise merchandise)
        {
            base.AddObject("Merchandises", merchandise);
        }
    
        /// <summary>
        /// 用于向 Staffs EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToStaffs(Staff staff)
        {
            base.AddObject("Staffs", staff);
        }
    
        /// <summary>
        /// 用于向 Stocks EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToStocks(Stock stock)
        {
            base.AddObject("Stocks", stock);
        }
    
        /// <summary>
        /// 用于向 Vendors EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToVendors(Vendor vendor)
        {
            base.AddObject("Vendors", vendor);
        }
    
        /// <summary>
        /// 用于向 Works EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToWorks(Work work)
        {
            base.AddObject("Works", work);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreDBModel", Name="ChainStore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChainStore : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ChainStore 对象。
        /// </summary>
        /// <param name="storeID">StoreID 属性的初始值。</param>
        public static ChainStore CreateChainStore(global::System.Int32 storeID)
        {
            ChainStore chainStore = new ChainStore();
            chainStore.StoreID = storeID;
            return chainStore;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoreID
        {
            get
            {
                return _StoreID;
            }
            set
            {
                if (_StoreID != value)
                {
                    OnStoreIDChanging(value);
                    ReportPropertyChanging("StoreID");
                    _StoreID = StructuralObject.SetValidValue(value, "StoreID");
                    ReportPropertyChanged("StoreID");
                    OnStoreIDChanged();
                }
            }
        }
        private global::System.Int32 _StoreID;
        partial void OnStoreIDChanging(global::System.Int32 value);
        partial void OnStoreIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreAddr
        {
            get
            {
                return _StoreAddr;
            }
            set
            {
                OnStoreAddrChanging(value);
                ReportPropertyChanging("StoreAddr");
                _StoreAddr = StructuralObject.SetValidValue(value, true, "StoreAddr");
                ReportPropertyChanged("StoreAddr");
                OnStoreAddrChanged();
            }
        }
        private global::System.String _StoreAddr;
        partial void OnStoreAddrChanging(global::System.String value);
        partial void OnStoreAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> StorePhoneNO
        {
            get
            {
                return _StorePhoneNO;
            }
            set
            {
                OnStorePhoneNOChanging(value);
                ReportPropertyChanging("StorePhoneNO");
                _StorePhoneNO = StructuralObject.SetValidValue(value, "StorePhoneNO");
                ReportPropertyChanged("StorePhoneNO");
                OnStorePhoneNOChanged();
            }
        }
        private Nullable<global::System.Int64> _StorePhoneNO;
        partial void OnStorePhoneNOChanging(Nullable<global::System.Int64> value);
        partial void OnStorePhoneNOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StaffQuantity
        {
            get
            {
                return _StaffQuantity;
            }
            set
            {
                OnStaffQuantityChanging(value);
                ReportPropertyChanging("StaffQuantity");
                _StaffQuantity = StructuralObject.SetValidValue(value, "StaffQuantity");
                ReportPropertyChanged("StaffQuantity");
                OnStaffQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _StaffQuantity;
        partial void OnStaffQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnStaffQuantityChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Inventory__Store__21B6055D", "Inventory")]
        public EntityCollection<Inventory> Inventories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Inventory>("StoreDBModel.FK__Inventory__Store__21B6055D", "Inventory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Inventory>("StoreDBModel.FK__Inventory__Store__21B6055D", "Inventory", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Merchandi__Store__173876EA", "Merchandise")]
        public EntityCollection<Merchandise> Merchandises
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Merchandise>("StoreDBModel.FK__Merchandi__Store__173876EA", "Merchandise");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Merchandise>("StoreDBModel.FK__Merchandi__Store__173876EA", "Merchandise", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Staff__StoreID__1273C1CD", "Staff")]
        public EntityCollection<Staff> Staffs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Staff>("StoreDBModel.FK__Staff__StoreID__1273C1CD", "Staff");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Staff>("StoreDBModel.FK__Staff__StoreID__1273C1CD", "Staff", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Work__StoreID__1DE57479", "Work")]
        public EntityCollection<Work> Works
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Work>("StoreDBModel.FK__Work__StoreID__1DE57479", "Work");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Work>("StoreDBModel.FK__Work__StoreID__1DE57479", "Work", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreDBModel", Name="Consume")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Consume : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Consume 对象。
        /// </summary>
        /// <param name="merchID">MerchID 属性的初始值。</param>
        /// <param name="memID">MemID 属性的初始值。</param>
        public static Consume CreateConsume(global::System.Int32 merchID, global::System.Int32 memID)
        {
            Consume consume = new Consume();
            consume.MerchID = merchID;
            consume.MemID = memID;
            return consume;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MerchID
        {
            get
            {
                return _MerchID;
            }
            set
            {
                if (_MerchID != value)
                {
                    OnMerchIDChanging(value);
                    ReportPropertyChanging("MerchID");
                    _MerchID = StructuralObject.SetValidValue(value, "MerchID");
                    ReportPropertyChanged("MerchID");
                    OnMerchIDChanged();
                }
            }
        }
        private global::System.Int32 _MerchID;
        partial void OnMerchIDChanging(global::System.Int32 value);
        partial void OnMerchIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemID
        {
            get
            {
                return _MemID;
            }
            set
            {
                OnMemIDChanging(value);
                ReportPropertyChanging("MemID");
                _MemID = StructuralObject.SetValidValue(value, "MemID");
                ReportPropertyChanged("MemID");
                OnMemIDChanged();
            }
        }
        private global::System.Int32 _MemID;
        partial void OnMemIDChanging(global::System.Int32 value);
        partial void OnMemIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ConDATE
        {
            get
            {
                return _ConDATE;
            }
            set
            {
                OnConDATEChanging(value);
                ReportPropertyChanging("ConDATE");
                _ConDATE = StructuralObject.SetValidValue(value, "ConDATE");
                ReportPropertyChanged("ConDATE");
                OnConDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _ConDATE;
        partial void OnConDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnConDATEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ConAmount
        {
            get
            {
                return _ConAmount;
            }
            set
            {
                OnConAmountChanging(value);
                ReportPropertyChanging("ConAmount");
                _ConAmount = StructuralObject.SetValidValue(value, "ConAmount");
                ReportPropertyChanged("ConAmount");
                OnConAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _ConAmount;
        partial void OnConAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnConAmountChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Consume__MemID__25869641", "Member")]
        public Member Member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("StoreDBModel.FK__Consume__MemID__25869641", "Member").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("StoreDBModel.FK__Consume__MemID__25869641", "Member").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Member> MemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("StoreDBModel.FK__Consume__MemID__25869641", "Member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Member>("StoreDBModel.FK__Consume__MemID__25869641", "Member", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Consume__MerchID__24927208", "Merchandise")]
        public Merchandise Merchandise
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandise>("StoreDBModel.FK__Consume__MerchID__24927208", "Merchandise").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandise>("StoreDBModel.FK__Consume__MerchID__24927208", "Merchandise").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Merchandise> MerchandiseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandise>("StoreDBModel.FK__Consume__MerchID__24927208", "Merchandise");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Merchandise>("StoreDBModel.FK__Consume__MerchID__24927208", "Merchandise", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreDBModel", Name="Inventory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Inventory : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Inventory 对象。
        /// </summary>
        /// <param name="merchID">MerchID 属性的初始值。</param>
        /// <param name="storeID">StoreID 属性的初始值。</param>
        public static Inventory CreateInventory(global::System.Int32 merchID, global::System.Int32 storeID)
        {
            Inventory inventory = new Inventory();
            inventory.MerchID = merchID;
            inventory.StoreID = storeID;
            return inventory;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MerchID
        {
            get
            {
                return _MerchID;
            }
            set
            {
                if (_MerchID != value)
                {
                    OnMerchIDChanging(value);
                    ReportPropertyChanging("MerchID");
                    _MerchID = StructuralObject.SetValidValue(value, "MerchID");
                    ReportPropertyChanged("MerchID");
                    OnMerchIDChanged();
                }
            }
        }
        private global::System.Int32 _MerchID;
        partial void OnMerchIDChanging(global::System.Int32 value);
        partial void OnMerchIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoreID
        {
            get
            {
                return _StoreID;
            }
            set
            {
                OnStoreIDChanging(value);
                ReportPropertyChanging("StoreID");
                _StoreID = StructuralObject.SetValidValue(value, "StoreID");
                ReportPropertyChanged("StoreID");
                OnStoreIDChanged();
            }
        }
        private global::System.Int32 _StoreID;
        partial void OnStoreIDChanging(global::System.Int32 value);
        partial void OnStoreIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InvenQuantity
        {
            get
            {
                return _InvenQuantity;
            }
            set
            {
                OnInvenQuantityChanging(value);
                ReportPropertyChanging("InvenQuantity");
                _InvenQuantity = StructuralObject.SetValidValue(value, "InvenQuantity");
                ReportPropertyChanged("InvenQuantity");
                OnInvenQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _InvenQuantity;
        partial void OnInvenQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnInvenQuantityChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Inventory__Store__21B6055D", "ChainStore")]
        public ChainStore ChainStore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Inventory__Store__21B6055D", "ChainStore").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Inventory__Store__21B6055D", "ChainStore").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ChainStore> ChainStoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Inventory__Store__21B6055D", "ChainStore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ChainStore>("StoreDBModel.FK__Inventory__Store__21B6055D", "ChainStore", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Inventory__Merch__20C1E124", "Merchandise")]
        public Merchandise Merchandise
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandise>("StoreDBModel.FK__Inventory__Merch__20C1E124", "Merchandise").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandise>("StoreDBModel.FK__Inventory__Merch__20C1E124", "Merchandise").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Merchandise> MerchandiseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandise>("StoreDBModel.FK__Inventory__Merch__20C1E124", "Merchandise");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Merchandise>("StoreDBModel.FK__Inventory__Merch__20C1E124", "Merchandise", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreDBModel", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Member 对象。
        /// </summary>
        /// <param name="memID">MemID 属性的初始值。</param>
        public static Member CreateMember(global::System.Int32 memID)
        {
            Member member = new Member();
            member.MemID = memID;
            return member;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemID
        {
            get
            {
                return _MemID;
            }
            set
            {
                if (_MemID != value)
                {
                    OnMemIDChanging(value);
                    ReportPropertyChanging("MemID");
                    _MemID = StructuralObject.SetValidValue(value, "MemID");
                    ReportPropertyChanged("MemID");
                    OnMemIDChanged();
                }
            }
        }
        private global::System.Int32 _MemID;
        partial void OnMemIDChanging(global::System.Int32 value);
        partial void OnMemIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MemName
        {
            get
            {
                return _MemName;
            }
            set
            {
                OnMemNameChanging(value);
                ReportPropertyChanging("MemName");
                _MemName = StructuralObject.SetValidValue(value, true, "MemName");
                ReportPropertyChanged("MemName");
                OnMemNameChanged();
            }
        }
        private global::System.String _MemName;
        partial void OnMemNameChanging(global::System.String value);
        partial void OnMemNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MemGender
        {
            get
            {
                return _MemGender;
            }
            set
            {
                OnMemGenderChanging(value);
                ReportPropertyChanging("MemGender");
                _MemGender = StructuralObject.SetValidValue(value, true, "MemGender");
                ReportPropertyChanged("MemGender");
                OnMemGenderChanged();
            }
        }
        private global::System.String _MemGender;
        partial void OnMemGenderChanging(global::System.String value);
        partial void OnMemGenderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MemAddr
        {
            get
            {
                return _MemAddr;
            }
            set
            {
                OnMemAddrChanging(value);
                ReportPropertyChanging("MemAddr");
                _MemAddr = StructuralObject.SetValidValue(value, true, "MemAddr");
                ReportPropertyChanged("MemAddr");
                OnMemAddrChanged();
            }
        }
        private global::System.String _MemAddr;
        partial void OnMemAddrChanging(global::System.String value);
        partial void OnMemAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MemPhoneNO
        {
            get
            {
                return _MemPhoneNO;
            }
            set
            {
                OnMemPhoneNOChanging(value);
                ReportPropertyChanging("MemPhoneNO");
                _MemPhoneNO = StructuralObject.SetValidValue(value, "MemPhoneNO");
                ReportPropertyChanged("MemPhoneNO");
                OnMemPhoneNOChanged();
            }
        }
        private Nullable<global::System.Int64> _MemPhoneNO;
        partial void OnMemPhoneNOChanging(Nullable<global::System.Int64> value);
        partial void OnMemPhoneNOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CardNO
        {
            get
            {
                return _CardNO;
            }
            set
            {
                OnCardNOChanging(value);
                ReportPropertyChanging("CardNO");
                _CardNO = StructuralObject.SetValidValue(value, "CardNO");
                ReportPropertyChanged("CardNO");
                OnCardNOChanged();
            }
        }
        private Nullable<global::System.Int64> _CardNO;
        partial void OnCardNOChanging(Nullable<global::System.Int64> value);
        partial void OnCardNOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegistrationDATE
        {
            get
            {
                return _RegistrationDATE;
            }
            set
            {
                OnRegistrationDATEChanging(value);
                ReportPropertyChanging("RegistrationDATE");
                _RegistrationDATE = StructuralObject.SetValidValue(value, "RegistrationDATE");
                ReportPropertyChanged("RegistrationDATE");
                OnRegistrationDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegistrationDATE;
        partial void OnRegistrationDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnRegistrationDATEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TotalAmount
        {
            get
            {
                return _TotalAmount;
            }
            set
            {
                OnTotalAmountChanging(value);
                ReportPropertyChanging("TotalAmount");
                _TotalAmount = StructuralObject.SetValidValue(value, "TotalAmount");
                ReportPropertyChanged("TotalAmount");
                OnTotalAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _TotalAmount;
        partial void OnTotalAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnTotalAmountChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Consume__MemID__25869641", "Consume")]
        public EntityCollection<Consume> Consumes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Consume>("StoreDBModel.FK__Consume__MemID__25869641", "Consume");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Consume>("StoreDBModel.FK__Consume__MemID__25869641", "Consume", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreDBModel", Name="Merchandise")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Merchandise : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Merchandise 对象。
        /// </summary>
        /// <param name="merchID">MerchID 属性的初始值。</param>
        /// <param name="storeID">StoreID 属性的初始值。</param>
        /// <param name="vendorID">VendorID 属性的初始值。</param>
        public static Merchandise CreateMerchandise(global::System.Int32 merchID, global::System.Int32 storeID, global::System.Int32 vendorID)
        {
            Merchandise merchandise = new Merchandise();
            merchandise.MerchID = merchID;
            merchandise.StoreID = storeID;
            merchandise.VendorID = vendorID;
            return merchandise;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MerchID
        {
            get
            {
                return _MerchID;
            }
            set
            {
                if (_MerchID != value)
                {
                    OnMerchIDChanging(value);
                    ReportPropertyChanging("MerchID");
                    _MerchID = StructuralObject.SetValidValue(value, "MerchID");
                    ReportPropertyChanged("MerchID");
                    OnMerchIDChanged();
                }
            }
        }
        private global::System.Int32 _MerchID;
        partial void OnMerchIDChanging(global::System.Int32 value);
        partial void OnMerchIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoreID
        {
            get
            {
                return _StoreID;
            }
            set
            {
                OnStoreIDChanging(value);
                ReportPropertyChanging("StoreID");
                _StoreID = StructuralObject.SetValidValue(value, "StoreID");
                ReportPropertyChanged("StoreID");
                OnStoreIDChanged();
            }
        }
        private global::System.Int32 _StoreID;
        partial void OnStoreIDChanging(global::System.Int32 value);
        partial void OnStoreIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VendorID
        {
            get
            {
                return _VendorID;
            }
            set
            {
                OnVendorIDChanging(value);
                ReportPropertyChanging("VendorID");
                _VendorID = StructuralObject.SetValidValue(value, "VendorID");
                ReportPropertyChanged("VendorID");
                OnVendorIDChanged();
            }
        }
        private global::System.Int32 _VendorID;
        partial void OnVendorIDChanging(global::System.Int32 value);
        partial void OnVendorIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchName
        {
            get
            {
                return _MerchName;
            }
            set
            {
                OnMerchNameChanging(value);
                ReportPropertyChanging("MerchName");
                _MerchName = StructuralObject.SetValidValue(value, true, "MerchName");
                ReportPropertyChanged("MerchName");
                OnMerchNameChanged();
            }
        }
        private global::System.String _MerchName;
        partial void OnMerchNameChanging(global::System.String value);
        partial void OnMerchNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MerchPrice
        {
            get
            {
                return _MerchPrice;
            }
            set
            {
                OnMerchPriceChanging(value);
                ReportPropertyChanging("MerchPrice");
                _MerchPrice = StructuralObject.SetValidValue(value, "MerchPrice");
                ReportPropertyChanged("MerchPrice");
                OnMerchPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _MerchPrice;
        partial void OnMerchPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnMerchPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> BarCode
        {
            get
            {
                return _BarCode;
            }
            set
            {
                OnBarCodeChanging(value);
                ReportPropertyChanging("BarCode");
                _BarCode = StructuralObject.SetValidValue(value, "BarCode");
                ReportPropertyChanged("BarCode");
                OnBarCodeChanged();
            }
        }
        private Nullable<global::System.Int64> _BarCode;
        partial void OnBarCodeChanging(Nullable<global::System.Int64> value);
        partial void OnBarCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PromotionPrice
        {
            get
            {
                return _PromotionPrice;
            }
            set
            {
                OnPromotionPriceChanging(value);
                ReportPropertyChanging("PromotionPrice");
                _PromotionPrice = StructuralObject.SetValidValue(value, "PromotionPrice");
                ReportPropertyChanged("PromotionPrice");
                OnPromotionPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _PromotionPrice;
        partial void OnPromotionPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPromotionPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PromotionDATES
        {
            get
            {
                return _PromotionDATES;
            }
            set
            {
                OnPromotionDATESChanging(value);
                ReportPropertyChanging("PromotionDATES");
                _PromotionDATES = StructuralObject.SetValidValue(value, "PromotionDATES");
                ReportPropertyChanged("PromotionDATES");
                OnPromotionDATESChanged();
            }
        }
        private Nullable<global::System.DateTime> _PromotionDATES;
        partial void OnPromotionDATESChanging(Nullable<global::System.DateTime> value);
        partial void OnPromotionDATESChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PromotionDATEE
        {
            get
            {
                return _PromotionDATEE;
            }
            set
            {
                OnPromotionDATEEChanging(value);
                ReportPropertyChanging("PromotionDATEE");
                _PromotionDATEE = StructuralObject.SetValidValue(value, "PromotionDATEE");
                ReportPropertyChanged("PromotionDATEE");
                OnPromotionDATEEChanged();
            }
        }
        private Nullable<global::System.DateTime> _PromotionDATEE;
        partial void OnPromotionDATEEChanging(Nullable<global::System.DateTime> value);
        partial void OnPromotionDATEEChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Merchandi__Store__173876EA", "ChainStore")]
        public ChainStore ChainStore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Merchandi__Store__173876EA", "ChainStore").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Merchandi__Store__173876EA", "ChainStore").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ChainStore> ChainStoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Merchandi__Store__173876EA", "ChainStore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ChainStore>("StoreDBModel.FK__Merchandi__Store__173876EA", "ChainStore", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Consume__MerchID__24927208", "Consume")]
        public Consume Consume
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consume>("StoreDBModel.FK__Consume__MerchID__24927208", "Consume").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consume>("StoreDBModel.FK__Consume__MerchID__24927208", "Consume").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Consume> ConsumeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Consume>("StoreDBModel.FK__Consume__MerchID__24927208", "Consume");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Consume>("StoreDBModel.FK__Consume__MerchID__24927208", "Consume", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Inventory__Merch__20C1E124", "Inventory")]
        public Inventory Inventory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Inventory>("StoreDBModel.FK__Inventory__Merch__20C1E124", "Inventory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Inventory>("StoreDBModel.FK__Inventory__Merch__20C1E124", "Inventory").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Inventory> InventoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Inventory>("StoreDBModel.FK__Inventory__Merch__20C1E124", "Inventory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Inventory>("StoreDBModel.FK__Inventory__Merch__20C1E124", "Inventory", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Merchandi__Vendo__182C9B23", "Vendor")]
        public Vendor Vendor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("StoreDBModel.FK__Merchandi__Vendo__182C9B23", "Vendor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("StoreDBModel.FK__Merchandi__Vendo__182C9B23", "Vendor").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vendor> VendorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("StoreDBModel.FK__Merchandi__Vendo__182C9B23", "Vendor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vendor>("StoreDBModel.FK__Merchandi__Vendo__182C9B23", "Vendor", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Stock__MerchID__286302EC", "Stock")]
        public Stock Stock
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("StoreDBModel.FK__Stock__MerchID__286302EC", "Stock").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("StoreDBModel.FK__Stock__MerchID__286302EC", "Stock").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Stock> StockReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("StoreDBModel.FK__Stock__MerchID__286302EC", "Stock");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Stock>("StoreDBModel.FK__Stock__MerchID__286302EC", "Stock", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreDBModel", Name="Staff")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Staff : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Staff 对象。
        /// </summary>
        /// <param name="staffID">StaffID 属性的初始值。</param>
        /// <param name="storeID">StoreID 属性的初始值。</param>
        public static Staff CreateStaff(global::System.Int32 staffID, global::System.Int32 storeID)
        {
            Staff staff = new Staff();
            staff.StaffID = staffID;
            staff.StoreID = storeID;
            return staff;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StaffID
        {
            get
            {
                return _StaffID;
            }
            set
            {
                if (_StaffID != value)
                {
                    OnStaffIDChanging(value);
                    ReportPropertyChanging("StaffID");
                    _StaffID = StructuralObject.SetValidValue(value, "StaffID");
                    ReportPropertyChanged("StaffID");
                    OnStaffIDChanged();
                }
            }
        }
        private global::System.Int32 _StaffID;
        partial void OnStaffIDChanging(global::System.Int32 value);
        partial void OnStaffIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoreID
        {
            get
            {
                return _StoreID;
            }
            set
            {
                OnStoreIDChanging(value);
                ReportPropertyChanging("StoreID");
                _StoreID = StructuralObject.SetValidValue(value, "StoreID");
                ReportPropertyChanged("StoreID");
                OnStoreIDChanged();
            }
        }
        private global::System.Int32 _StoreID;
        partial void OnStoreIDChanging(global::System.Int32 value);
        partial void OnStoreIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StaffName
        {
            get
            {
                return _StaffName;
            }
            set
            {
                OnStaffNameChanging(value);
                ReportPropertyChanging("StaffName");
                _StaffName = StructuralObject.SetValidValue(value, true, "StaffName");
                ReportPropertyChanged("StaffName");
                OnStaffNameChanged();
            }
        }
        private global::System.String _StaffName;
        partial void OnStaffNameChanging(global::System.String value);
        partial void OnStaffNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StaffGender
        {
            get
            {
                return _StaffGender;
            }
            set
            {
                OnStaffGenderChanging(value);
                ReportPropertyChanging("StaffGender");
                _StaffGender = StructuralObject.SetValidValue(value, true, "StaffGender");
                ReportPropertyChanged("StaffGender");
                OnStaffGenderChanged();
            }
        }
        private global::System.String _StaffGender;
        partial void OnStaffGenderChanging(global::System.String value);
        partial void OnStaffGenderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StaffAge
        {
            get
            {
                return _StaffAge;
            }
            set
            {
                OnStaffAgeChanging(value);
                ReportPropertyChanging("StaffAge");
                _StaffAge = StructuralObject.SetValidValue(value, "StaffAge");
                ReportPropertyChanged("StaffAge");
                OnStaffAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _StaffAge;
        partial void OnStaffAgeChanging(Nullable<global::System.Int32> value);
        partial void OnStaffAgeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StaffWage
        {
            get
            {
                return _StaffWage;
            }
            set
            {
                OnStaffWageChanging(value);
                ReportPropertyChanging("StaffWage");
                _StaffWage = StructuralObject.SetValidValue(value, "StaffWage");
                ReportPropertyChanged("StaffWage");
                OnStaffWageChanged();
            }
        }
        private Nullable<global::System.Decimal> _StaffWage;
        partial void OnStaffWageChanging(Nullable<global::System.Decimal> value);
        partial void OnStaffWageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StaffAddr
        {
            get
            {
                return _StaffAddr;
            }
            set
            {
                OnStaffAddrChanging(value);
                ReportPropertyChanging("StaffAddr");
                _StaffAddr = StructuralObject.SetValidValue(value, true, "StaffAddr");
                ReportPropertyChanged("StaffAddr");
                OnStaffAddrChanged();
            }
        }
        private global::System.String _StaffAddr;
        partial void OnStaffAddrChanging(global::System.String value);
        partial void OnStaffAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> StaffPhoneNO
        {
            get
            {
                return _StaffPhoneNO;
            }
            set
            {
                OnStaffPhoneNOChanging(value);
                ReportPropertyChanging("StaffPhoneNO");
                _StaffPhoneNO = StructuralObject.SetValidValue(value, "StaffPhoneNO");
                ReportPropertyChanged("StaffPhoneNO");
                OnStaffPhoneNOChanged();
            }
        }
        private Nullable<global::System.Int64> _StaffPhoneNO;
        partial void OnStaffPhoneNOChanging(Nullable<global::System.Int64> value);
        partial void OnStaffPhoneNOChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Staff__StoreID__1273C1CD", "ChainStore")]
        public ChainStore ChainStore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Staff__StoreID__1273C1CD", "ChainStore").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Staff__StoreID__1273C1CD", "ChainStore").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ChainStore> ChainStoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Staff__StoreID__1273C1CD", "ChainStore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ChainStore>("StoreDBModel.FK__Staff__StoreID__1273C1CD", "ChainStore", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Work__StaffID__1CF15040", "Work")]
        public Work Work
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Work>("StoreDBModel.FK__Work__StaffID__1CF15040", "Work").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Work>("StoreDBModel.FK__Work__StaffID__1CF15040", "Work").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Work> WorkReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Work>("StoreDBModel.FK__Work__StaffID__1CF15040", "Work");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Work>("StoreDBModel.FK__Work__StaffID__1CF15040", "Work", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreDBModel", Name="Stock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stock : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Stock 对象。
        /// </summary>
        /// <param name="merchID">MerchID 属性的初始值。</param>
        /// <param name="vendorID">VendorID 属性的初始值。</param>
        public static Stock CreateStock(global::System.Int32 merchID, global::System.Int32 vendorID)
        {
            Stock stock = new Stock();
            stock.MerchID = merchID;
            stock.VendorID = vendorID;
            return stock;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MerchID
        {
            get
            {
                return _MerchID;
            }
            set
            {
                if (_MerchID != value)
                {
                    OnMerchIDChanging(value);
                    ReportPropertyChanging("MerchID");
                    _MerchID = StructuralObject.SetValidValue(value, "MerchID");
                    ReportPropertyChanged("MerchID");
                    OnMerchIDChanged();
                }
            }
        }
        private global::System.Int32 _MerchID;
        partial void OnMerchIDChanging(global::System.Int32 value);
        partial void OnMerchIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VendorID
        {
            get
            {
                return _VendorID;
            }
            set
            {
                OnVendorIDChanging(value);
                ReportPropertyChanging("VendorID");
                _VendorID = StructuralObject.SetValidValue(value, "VendorID");
                ReportPropertyChanged("VendorID");
                OnVendorIDChanged();
            }
        }
        private global::System.Int32 _VendorID;
        partial void OnVendorIDChanging(global::System.Int32 value);
        partial void OnVendorIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StockDATE
        {
            get
            {
                return _StockDATE;
            }
            set
            {
                OnStockDATEChanging(value);
                ReportPropertyChanging("StockDATE");
                _StockDATE = StructuralObject.SetValidValue(value, "StockDATE");
                ReportPropertyChanged("StockDATE");
                OnStockDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _StockDATE;
        partial void OnStockDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnStockDATEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StockQuantity
        {
            get
            {
                return _StockQuantity;
            }
            set
            {
                OnStockQuantityChanging(value);
                ReportPropertyChanging("StockQuantity");
                _StockQuantity = StructuralObject.SetValidValue(value, "StockQuantity");
                ReportPropertyChanged("StockQuantity");
                OnStockQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _StockQuantity;
        partial void OnStockQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnStockQuantityChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Stock__MerchID__286302EC", "Merchandise")]
        public Merchandise Merchandise
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandise>("StoreDBModel.FK__Stock__MerchID__286302EC", "Merchandise").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandise>("StoreDBModel.FK__Stock__MerchID__286302EC", "Merchandise").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Merchandise> MerchandiseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merchandise>("StoreDBModel.FK__Stock__MerchID__286302EC", "Merchandise");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Merchandise>("StoreDBModel.FK__Stock__MerchID__286302EC", "Merchandise", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Stock__VendorID__29572725", "Vendor")]
        public Vendor Vendor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("StoreDBModel.FK__Stock__VendorID__29572725", "Vendor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("StoreDBModel.FK__Stock__VendorID__29572725", "Vendor").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vendor> VendorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vendor>("StoreDBModel.FK__Stock__VendorID__29572725", "Vendor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vendor>("StoreDBModel.FK__Stock__VendorID__29572725", "Vendor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreDBModel", Name="Vendor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vendor : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Vendor 对象。
        /// </summary>
        /// <param name="vendorID">VendorID 属性的初始值。</param>
        public static Vendor CreateVendor(global::System.Int32 vendorID)
        {
            Vendor vendor = new Vendor();
            vendor.VendorID = vendorID;
            return vendor;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VendorID
        {
            get
            {
                return _VendorID;
            }
            set
            {
                if (_VendorID != value)
                {
                    OnVendorIDChanging(value);
                    ReportPropertyChanging("VendorID");
                    _VendorID = StructuralObject.SetValidValue(value, "VendorID");
                    ReportPropertyChanged("VendorID");
                    OnVendorIDChanged();
                }
            }
        }
        private global::System.Int32 _VendorID;
        partial void OnVendorIDChanging(global::System.Int32 value);
        partial void OnVendorIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VendorName
        {
            get
            {
                return _VendorName;
            }
            set
            {
                OnVendorNameChanging(value);
                ReportPropertyChanging("VendorName");
                _VendorName = StructuralObject.SetValidValue(value, true, "VendorName");
                ReportPropertyChanged("VendorName");
                OnVendorNameChanged();
            }
        }
        private global::System.String _VendorName;
        partial void OnVendorNameChanging(global::System.String value);
        partial void OnVendorNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VendorAddr
        {
            get
            {
                return _VendorAddr;
            }
            set
            {
                OnVendorAddrChanging(value);
                ReportPropertyChanging("VendorAddr");
                _VendorAddr = StructuralObject.SetValidValue(value, true, "VendorAddr");
                ReportPropertyChanged("VendorAddr");
                OnVendorAddrChanged();
            }
        }
        private global::System.String _VendorAddr;
        partial void OnVendorAddrChanging(global::System.String value);
        partial void OnVendorAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> VendorPhoneNO
        {
            get
            {
                return _VendorPhoneNO;
            }
            set
            {
                OnVendorPhoneNOChanging(value);
                ReportPropertyChanging("VendorPhoneNO");
                _VendorPhoneNO = StructuralObject.SetValidValue(value, "VendorPhoneNO");
                ReportPropertyChanged("VendorPhoneNO");
                OnVendorPhoneNOChanged();
            }
        }
        private Nullable<global::System.Int64> _VendorPhoneNO;
        partial void OnVendorPhoneNOChanging(Nullable<global::System.Int64> value);
        partial void OnVendorPhoneNOChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Merchandi__Vendo__182C9B23", "Merchandise")]
        public EntityCollection<Merchandise> Merchandises
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Merchandise>("StoreDBModel.FK__Merchandi__Vendo__182C9B23", "Merchandise");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Merchandise>("StoreDBModel.FK__Merchandi__Vendo__182C9B23", "Merchandise", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Stock__VendorID__29572725", "Stock")]
        public EntityCollection<Stock> Stocks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Stock>("StoreDBModel.FK__Stock__VendorID__29572725", "Stock");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Stock>("StoreDBModel.FK__Stock__VendorID__29572725", "Stock", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoreDBModel", Name="Work")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Work : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Work 对象。
        /// </summary>
        /// <param name="staffID">StaffID 属性的初始值。</param>
        /// <param name="storeID">StoreID 属性的初始值。</param>
        public static Work CreateWork(global::System.Int32 staffID, global::System.Int32 storeID)
        {
            Work work = new Work();
            work.StaffID = staffID;
            work.StoreID = storeID;
            return work;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StaffID
        {
            get
            {
                return _StaffID;
            }
            set
            {
                if (_StaffID != value)
                {
                    OnStaffIDChanging(value);
                    ReportPropertyChanging("StaffID");
                    _StaffID = StructuralObject.SetValidValue(value, "StaffID");
                    ReportPropertyChanged("StaffID");
                    OnStaffIDChanged();
                }
            }
        }
        private global::System.Int32 _StaffID;
        partial void OnStaffIDChanging(global::System.Int32 value);
        partial void OnStaffIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoreID
        {
            get
            {
                return _StoreID;
            }
            set
            {
                OnStoreIDChanging(value);
                ReportPropertyChanging("StoreID");
                _StoreID = StructuralObject.SetValidValue(value, "StoreID");
                ReportPropertyChanged("StoreID");
                OnStoreIDChanged();
            }
        }
        private global::System.Int32 _StoreID;
        partial void OnStoreIDChanging(global::System.Int32 value);
        partial void OnStoreIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HireDATE
        {
            get
            {
                return _HireDATE;
            }
            set
            {
                OnHireDATEChanging(value);
                ReportPropertyChanging("HireDATE");
                _HireDATE = StructuralObject.SetValidValue(value, "HireDATE");
                ReportPropertyChanged("HireDATE");
                OnHireDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _HireDATE;
        partial void OnHireDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnHireDATEChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AwardsRecords
        {
            get
            {
                return _AwardsRecords;
            }
            set
            {
                OnAwardsRecordsChanging(value);
                ReportPropertyChanging("AwardsRecords");
                _AwardsRecords = StructuralObject.SetValidValue(value, true, "AwardsRecords");
                ReportPropertyChanged("AwardsRecords");
                OnAwardsRecordsChanged();
            }
        }
        private global::System.String _AwardsRecords;
        partial void OnAwardsRecordsChanging(global::System.String value);
        partial void OnAwardsRecordsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PunishmentRecords
        {
            get
            {
                return _PunishmentRecords;
            }
            set
            {
                OnPunishmentRecordsChanging(value);
                ReportPropertyChanging("PunishmentRecords");
                _PunishmentRecords = StructuralObject.SetValidValue(value, true, "PunishmentRecords");
                ReportPropertyChanged("PunishmentRecords");
                OnPunishmentRecordsChanged();
            }
        }
        private global::System.String _PunishmentRecords;
        partial void OnPunishmentRecordsChanging(global::System.String value);
        partial void OnPunishmentRecordsChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Work__StoreID__1DE57479", "ChainStore")]
        public ChainStore ChainStore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Work__StoreID__1DE57479", "ChainStore").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Work__StoreID__1DE57479", "ChainStore").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ChainStore> ChainStoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ChainStore>("StoreDBModel.FK__Work__StoreID__1DE57479", "ChainStore");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ChainStore>("StoreDBModel.FK__Work__StoreID__1DE57479", "ChainStore", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StoreDBModel", "FK__Work__StaffID__1CF15040", "Staff")]
        public Staff Staff
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Staff>("StoreDBModel.FK__Work__StaffID__1CF15040", "Staff").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Staff>("StoreDBModel.FK__Work__StaffID__1CF15040", "Staff").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Staff> StaffReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Staff>("StoreDBModel.FK__Work__StaffID__1CF15040", "Staff");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Staff>("StoreDBModel.FK__Work__StaffID__1CF15040", "Staff", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
