//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarketer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Merchandises = new HashSet<Merchandise>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int VendorID { get; set; }
        public string VendorName { get; set; }
        public string VendorAddr { get; set; }
        public Nullable<int> VendorPhoneNO { get; set; }
    
        public virtual ICollection<Merchandise> Merchandises { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
